# LEARING

Youtube

In [2]:
import numpy as np

基于矩阵的运算，相比较于数列...的运算而言要快多达十几倍

In [3]:
array = np.array([[1,2,3],[2,3,4]])

In [4]:
print(array)

[[1 2 3]
 [2 3 4]]


数组定义一个矩阵,一般用列表--
array 没有用逗号来区分～～～

In [5]:
print('number of dim:(维度)', array.ndim)
print('shapy', array.shape)
print('size', array.size)

number of dim:(维度) 2
shapy (2, 3)
size 6


In [15]:
a = np.array([2,23,4], np.int)
print(a.dtype)
a = np.array([2,23,4], np.int32)
print(a.dtype)
a = np.array([2,23,4], np.float)
print(a.dtype)

int64
int32
float64


在创建一个新的矩阵array/a 的同时，定义这个数的类型
int默认为64位
32位输入
a = np.array([2,23,4], np.int32)
位数越小 需要空间越大， 64 需要的空间大于 32，精度越高

In [34]:
a = np.zeros((3,4)) #用括号表示 几行几列的array，生成的形式类似于Matlab
print(a)
a = np.ones((3,4), np.float)
print(a, a.dtype)
b = np.empty((2,2))
print(b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] float64
[[1.28822975e-231 2.32035667e+077]
 [1.48219694e-323 4.17201348e-309]]


In [47]:
a = np.arange(10,22,2) #类比于range
print(a)
b = a.reshape(2,3)
print(b)

[10 12 14 16 18 20]
[[10 12 14]
 [16 18 20]]


In [48]:
np.zeros_like(a)
np.zeros_like(b)

array([[0, 0, 0],
       [0, 0, 0]])

In [51]:
a = np.linspace(1,10,20)
print(a)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


In [53]:
a.reshape(4,5)

array([[ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684],
       [ 3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789],
       [ 5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895],
       [ 8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ]])

In [58]:
a = np.array([1,2,3,4])
b = np.arange(2,6)
print(a)
print(b)

[1 2 3 4]
[2 3 4 5]


In [60]:
print(b - a)

[1 1 1 1]


In [61]:
c = 10*np.sin(a)
print(c)

[ 8.41470985  9.09297427  1.41120008 -7.56802495]


In [62]:
print(b)
print(b>2) #array中间的数值大小

[2 3 4 5]
[False  True  True  True]


In [64]:
a = np.array([[1,2],[3,4]])
b = np.arange(4).reshape(2,2)
print(a)
print(b)

[[1 2]
 [3 4]]
[[0 1]
 [2 3]]


In [68]:
c = a * b #逐个相乘
print(c)
c = np.dot(a,b) #矩阵乘法
print(c)
c = a.dot(b) #矩阵乘法的另一个表现形式
print(c)

[[ 0  2]
 [ 6 12]]
[[ 4  7]
 [ 8 15]]
[[ 4  7]
 [ 8 15]]


In [70]:
a = np.random.random((2,4)) #随机生成的数组 默认是0-1之间随机
print(a)

[[0.13140252 0.57637054 0.56647187 0.36106786]
 [0.90452665 0.84403363 0.36761712 0.81325886]]


In [71]:
print(a.dtype)

float64


In [76]:
print(np.sum(a),np.min(a),np.max(a))

4.564749047556193 0.13140251904656974 0.9045266491885493


In [77]:
print(np.sum(a,axis=1),np.min(a,axis=1),np.max(a,axis=1)) # axis=1行里求，axis=0列里求

[1.63531279 2.92943626] [0.13140252 0.36761712] [0.57637054 0.90452665]


In [89]:
a = np.arange(2,14).reshape(3,4)
print(a)
print(np.argmin(a))
print(np.argmax(a)) #位置索引
print(np.mean(a), a.mean(),np.average(a)) #平均值
print(np.median(a)) #中位数

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
0
11
7.5 7.5 7.5
7.5


In [92]:
print(a)
print(np.cumsum(a)) #累加
print(np.diff(a)) #累差 每一排单独

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]
[ 2  5  9 14 20 27 35 44 54 65 77 90]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [93]:
print(np.nonzero(a))

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2]), array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]))


第一个array表示行，第二个array表示列
一一对应的看，
比如array1 第一个表示第0行，array2第一个表示第0列
then 加在一起表示第0行第0列是一个非0数

In [96]:
b = np.zeros_like(a)
print(b)
print(np.nonzero(b))

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
(array([], dtype=int64), array([], dtype=int64))


In [102]:
a = np.random.random((2,3)) 
print(a)
print(np.sort(a)) #逐行排序

[[0.32290496 0.79684498 0.58044269]
 [0.16506094 0.69179906 0.29578873]]
[[0.32290496 0.58044269 0.79684498]
 [0.16506094 0.29578873 0.69179906]]


In [104]:
print(a)
print(np.transpose(a)) #对称 LA里面的T/transpose
print(a.T)

[[0.32290496 0.79684498 0.58044269]
 [0.16506094 0.69179906 0.29578873]]
[[0.32290496 0.16506094]
 [0.79684498 0.69179906]
 [0.58044269 0.29578873]]
[[0.32290496 0.16506094]
 [0.79684498 0.69179906]
 [0.58044269 0.29578873]]


In [105]:
print((a.T).dot(a))

[[0.13151273 0.3714942  0.23625099]
 [0.3714942  1.11354785 0.66714921]
 [0.23625099 0.66714921 0.42440469]]


In [106]:
# np.clip 取大取小 中间不变
print(a)
print(np.clip(a,0.3,0.5))

[[0.32290496 0.79684498 0.58044269]
 [0.16506094 0.69179906 0.29578873]]
[[0.32290496 0.5        0.5       ]
 [0.3        0.5        0.3       ]]


In [116]:
print(np.mean(a,axis=0,dtype=float))
print(np.mean(a,axis=0))
print(np.mean(a,axis=0).dtype)

0.4754735598944222
0.4754735598944222
float64


In [6]:
import numpy as np
a = np.arange(4).reshape(2,2)
print(a)

[[0 1]
 [2 3]]


In [7]:
a = np.delete(a, 1, axis=0)

In [8]:
print(a)

[[0 1]]


位置信息及运算

In [2]:
import numpy as np
A = np.arange(3,15)
print(A)

[ 3  4  5  6  7  8  9 10 11 12 13 14]


In [3]:
print(A[3])

6


In [9]:
A = A.reshape(3,4)
print(A)

[[ 3  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]


In [10]:
print(A[2])

[11 12 13 14]


In [12]:
print(A[1][1]) # 第一行第一列
print(A[1,1])

8
8


In [14]:
print(A[2,:]) # 类似于Matlab用法
print(A[1,2:3])

[11 12 13 14]
[9]


In [15]:
for i in A:     # 迭代行，没有直接的迭代列的方式
    print(i)

[3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]


In [16]:
for j in A.T:      # 用transpose迭代列
    print(j)

[ 3  7 11]
[ 4  8 12]
[ 5  9 13]
[ 6 10 14]


In [17]:
print(A.flatten())      # flat迭代器的内容
for item in A.flat:       # 迭代器 每一个数值都分开输出
    print(item)

[ 3  4  5  6  7  8  9 10 11 12 13 14]
3
4
5
6
7
8
9
10
11
12
13
14



array的合并


In [18]:
a = np.array([1,1,1])
b = np.array([2,2,2])

print(np.vstack((a,b)))  # vertical stack 上下的合并

[[1 1 1]
 [2 2 2]]


In [19]:
print(np.vstack((a,b)).shape)   # 合并出来的东西的形状

(2, 3)


In [20]:
print(np.hstack((a,b)))     # horizantal stack 左右合并

[1 1 1 2 2 2]


In [21]:
print(a.T) # 没用。。。对于单排的array不可以直接用

[1 1 1]


In [23]:
print(a.shape)
print(a[np.newaxis,:])
print(a[np.newaxis,:].shape)
print(a[:,np.newaxis])
print(a[:,np.newaxis].shape)

(3,)
[[1 1 1]]
(1, 3)
[[1]
 [1]
 [1]]
(3, 1)


In [26]:
print(np.hstack((a[:,np.newaxis],b[:,np.newaxis])))

[[1 2]
 [1 2]
 [1 2]]


In [28]:
print(a)
c = np.concatenate(([a],[b],[b],[a]),axis=0)
print(c)   # 必须加维度才可以相加减

[1 1 1]
[[1 1 1]
 [2 2 2]
 [2 2 2]
 [1 1 1]]




分割



In [33]:
A = np.arange(1,13).reshape(3,4)
print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [38]:
print(np.split(A,2,axis=1)) # 纵向分割 等量分割

[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12]])]


In [39]:
print(np.split(A,3,axis=0)) #横向分割 等量分割

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]


In [40]:
print(np.array_split(A,3,axis=1)) # 不等量分割

[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]]), array([[ 3],
       [ 7],
       [11]]), array([[ 4],
       [ 8],
       [12]])]


In [41]:
print(np.vsplit(A,3))   # 和之前合并相类似的分裂方式

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[ 9, 10, 11, 12]])]


In [42]:
print(np.hsplit(A,2))

[array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]]), array([[ 3,  4],
       [ 7,  8],
       [11, 12]])]



复制



In [43]:
a = np.arange(4)
b = a
c = a
d = b
print(a)

[0 1 2 3]


In [44]:
a[0] = 11
print(a)

[11  1  2  3]


In [45]:
b is a

True

In [46]:
print(b)

[11  1  2  3]


In [47]:
print(c)
print(d)

[11  1  2  3]
[11  1  2  3]


In [48]:
d[1:3] = [22,33]
print(a)

[11 22 33  3]


In [49]:
print(a)
print(b)
b = a.copy()    # 只赋值
b[3] = 44
print(a)
print(b)

[11 22 33  3]
[11 22 33  3]
[11 22 33  3]
[11 22 33 44]


In [50]:
b is a

False



pandas

numpy--数列；pandas--字典

In [51]:
import pandas as pd
import numpy as np

In [55]:
s = pd.Series([1,3,6,np.nan,44,1])
print(s)

0     1.0
1     3.0
2     6.0
3     NaN
4    44.0
5     1.0
dtype: float64


In [56]:
date= pd.date_range('20200730',periods=6)
print(date)

DatetimeIndex(['2020-07-30', '2020-07-31', '2020-08-01', '2020-08-02',
               '2020-08-03', '2020-08-04'],
              dtype='datetime64[ns]', freq='D')


In [64]:
df = pd.DataFrame(np.random.randn(6,4),index=date)
print(df)

                   0         1         2         3
2020-07-30 -0.822240 -0.776273  0.094436 -1.575930
2020-07-31  0.160726 -0.845465 -0.756553 -0.037574
2020-08-01 -0.731366  0.546201 -0.479778  1.108569
2020-08-02 -1.907959 -1.145371 -1.897131 -0.242114
2020-08-03 -2.336995  0.415412  1.625737 -1.934430
2020-08-04  0.547438 -1.594033  0.648611  0.093207


In [67]:
df = pd.DataFrame(np.random.randn(6,4),index=date,columns=['A','B','C','D'])
print(df)

                   A         B         C         D
2020-07-30  1.713217 -1.170430  1.393832 -1.687402
2020-07-31  0.383080 -0.072059 -0.010631  1.701421
2020-08-01 -0.344901 -0.471295 -0.815543 -0.797000
2020-08-02  0.545255  1.809432 -1.598088  1.706801
2020-08-03  0.167268 -1.114583  0.580237 -0.484595
2020-08-04  0.333912  2.693214  0.388706  2.222298


In [68]:
df = pd.DataFrame(np.random.randn(6,4))   # 默认
print(df)

          0         1         2         3
0 -0.394414 -1.486141  0.594232 -0.253652
1  0.075715 -0.828967 -0.150884  2.752993
2 -1.439569 -2.777757 -1.103105 -1.054660
3  0.107735 -0.532247 -0.067505 -1.689834
4 -0.062169 -0.115166  0.541372 -0.907754
5  0.186007  0.522196  0.567358  0.615277


In [100]:
df1 = pd.DataFrame({'A':1.,'B':pd.Timestamp('20200730'),'Ç':pd.Categorical(['test','train','tesr','tran'])})
print(df1)     # 用字典生成

     A          B      Ç
0  1.0 2020-07-30   test
1  1.0 2020-07-30  train
2  1.0 2020-07-30   tesr
3  1.0 2020-07-30   tran


In [71]:
print(df1.dtypes)

A           float64
B    datetime64[ns]
Ç          category
dtype: object


In [72]:
print(df1.index)
print(df1.columns)

RangeIndex(start=0, stop=4, step=1)
Index(['A', 'B', 'Ç'], dtype='object')


In [105]:
print(df1.values)

[[1.0 Timestamp('2020-07-30 00:00:00') 'test']
 [1.0 Timestamp('2020-07-30 00:00:00') 'train']
 [1.0 Timestamp('2020-07-30 00:00:00') 'tesr']
 [1.0 Timestamp('2020-07-30 00:00:00') 'tran']]


In [74]:
print(df1.describe())  # 只运算数字形式，忽略其他形式

         A
count  4.0
mean   1.0
std    0.0
min    1.0
25%    1.0
50%    1.0
75%    1.0
max    1.0


In [76]:
print(df1.T)

                     0                    1                    2  \
A                    1                    1                    1   
B  2020-07-30 00:00:00  2020-07-30 00:00:00  2020-07-30 00:00:00   
Ç                 test                train                 tesr   

                     3  
A                    1  
B  2020-07-30 00:00:00  
Ç                train  


In [80]:
print(df1)
print(df1.sort_index(axis=0,ascending=False))
print(df1.sort_index(axis=1,ascending=False)) # columns的index排序

     A          B      Ç
0  1.0 2020-07-30   test
1  1.0 2020-07-30  train
2  1.0 2020-07-30   tesr
3  1.0 2020-07-30  train
     A          B      Ç
3  1.0 2020-07-30  train
2  1.0 2020-07-30   tesr
1  1.0 2020-07-30  train
0  1.0 2020-07-30   test
       Ç          B    A
0   test 2020-07-30  1.0
1  train 2020-07-30  1.0
2   tesr 2020-07-30  1.0
3  train 2020-07-30  1.0


In [102]:
print(df1)
print(df1.sort_values(by=['C']))

     A          B      Ç
0  1.0 2020-07-30   test
1  1.0 2020-07-30  train
2  1.0 2020-07-30   tesr
3  1.0 2020-07-30   tran


KeyError: 'C'

In [104]:
df1.dtypes

A           float64
B    datetime64[ns]
Ç          category
dtype: object